version: '3.9'

services:
  db:
    image: mariadb
    hostname: db-server
    container_name: db-container
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    ports:
      - "3306:3306"

  app:
    depends_on:
      - db
    build: .docker/app
    env_file: .docker/app/.env
    hostname: app-server
    container_name: app-container
    volumes:
      - app-volume:/var/www/html
      - ./dist:/var/www/html/wp-content/themes/my-theme
      - ./.docker/app/setup.sh:/var/www/html/setup.sh
      - ./.data/log:/var/log/apache2:delegated
      - ./.data/app/wp-includes:/var/www/html/wp-includes:delegated
      - ./.data/app/wp-admin:/var/www/html/wp-admin:delegated
      - ./.data/app/uploads:/var/www/html/wp-content/uploads:delegated
#      - ./.htaccess:/var/www/html/.htaccess
    restart: always
    tty: true
    ports:
      - "8888:80"
      - "9091:9091"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - "8081:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
volumes:
  db-volume:
  app-volume:
