version: '3'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306

  apache:
     build:
       context: ./docker/apache
       dockerfile: dockerfile
     links:
       - db
     ports:
       - 8080:80
     restart: always
     environment:
       WORDPRESS_DIR: /var/www/html
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     volumes:
       - ./.data/log/:/var/log/apache2/
       - ./docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
       - ./docker/php/php.ini:/usr/local/etc/php/php.ini:cached
       - ./bin/:/var/www/bin/
       - ./.www/:/var/www/html/
       - ./my-theme/:/var/www/html/wp-content/themes/my-theme/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=wordpress
    links:
      - db
    ports:
      - 8081:80

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
