version: '3.7'

services:
  db:
    image: mariadb
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    ports:
      - "3306:3306"

  app:
    depends_on:
      - db
    build: .docker/app
    env_file: .docker/app/.env
    volumes:
      - app-volume:/var/www/html
      - theme-volume:/var/www/html/wp-content/themes/my-theme
      - ./.data/log:/var/log:delegated
      - ./.htaccess:/var/www/html/.htaccess
    restart: always
    tty: true
    ports:
      - "8888:80"
      - "9091:9091"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - "8081:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db-volume:
  app-volume:
  theme-volume:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    source:
      alpha: "./dist"
      beta: "volume://theme-volume"
      mode: "one-way-replica"
      configurationBeta:
        permissions:
          defaultOwner: "id:33" # as www-data
          defaultGroup: "id:33" # as www-data
          defaultFileMode: 0666
          defaultDirectoryMode: 0777
