version: '3.7'

services:
  db:
    image: mariadb
    volumes:
      - ./.data/db:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    ports:
      - "3306:3306"

  app:
    depends_on:
      - db
    build: ./docker/app
    command: bash -c "sh /var/www/bin/migrations.sh && apache2-foreground"
    volumes:
      - ./app/themes:/var/www/html/wp/wp-content/themes
      - ./app/.htaccess:/var/www/html/.htaccess
      - ./bin:/var/www/bin
      - ./.data/app:/var/www/html:delegated
      - ./.data/log/app/:/var/log/apache2/
      - ./.data/log/app/php/:/var/log/php/
    environment:
      WP_PATH: /var/www/html/wp
      WP_USER: admin
      WP_PASS: password
      WP_MAIL: test@example.com
      WP_URL: http://localhost:8888/wp/
      WP_NAME: Wordpress
      WP_DB_HOST: db:3306
      WP_DB_NAME: wordpress
      WP_DB_USER: wordpress
      WP_DB_PASS: wordpress
      WP_DB_PREF: wp_
      WP_THEME: my-theme
    restart: always
    tty: true
    ports:
      - "8888:80"
      - "9091:9091"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - "8081:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"